PATCH http://brook442-redesigned-fishstick-4p4q6qgp7rw3j667-3000.preview.app.github.dev/movies HTTP/1.1
content-type: application/json

{
  "title": "Homi di Ferru",
  "source": "http://alksdfjlsadfjlskad.com/akudhaskduas.mp4",
  "description": "Um filme que um homi tem uma armadura di ferru[pát]icpo",
  "thumb": "http://alksdfjlsadfjlskad.com/akudhaskduas.jpg"
}